Allow using variables in defaults.yml
colcon/colcon-defaults pull request #16
Opened 2019-04-09 20:55 UTC by jpsamper2009

This PR would allow, for example, to configure the path
to a toolchain file for workspaces with the same layout:

```
{
    "build": {
        "cmake-args": [
            '-DCMAKE_TOOLCHAIN_FILE="$CWD/path/to/toolchainfile.cmake"]
    },
}
```

- This PR stems from a conversation in https://github.com/ament/ament_cmake/issues/160#issuecomment-481004597
- I'm not sure this is the cleanest solution, but it was simpler than modifying all the different arguments parsers to find and replace instances of the supported variables, and I figured it would at least get the conversation started...
- We could probably do something similar for `colcon-mixin` and/or `colcon-metadata`

2019-04-19 20:16 UTC, jpsamper2009 commented
I found a workaround for my use-case (finding a toolchain file in the current workspace) by having a different cmake file, call it `find_toolchain.cmake`, which I place in a known location like `/etc/colcon`. Then my `defaults.yaml` looks something like:

```
{
    "build": {
        "cmake-args": [
            '-DCMAKE_TOOLCHAIN_FILE="/etc/colcon/find_toolchain.cmake"]
    },
}
```

The `find_toolchain.cmake` make some weak assumptions about our workspace (i.e. it looks for a specific folder name) in order to find the toolchain file. Then it calls `include(${TOOLCHAIN_FILE})`. The weak assumptions could be minimized if there was a way to introspect from what directory `colcon` was called.

2019-06-03 15:57 UTC, dirk-thomas commented on colcon_defaults/argument_parser/defaults.py
> +            content = content.replace(k, v)
This simple replacement also modifies an input string like "$CWDfoo".

2019-06-03 15:58 UTC, dirk-thomas requested changes
See inline comment.

2019-07-31 23:12 UTC, dirk-thomas commented
@jpsamper2009 Friendly ping.

2019-09-02 04:06 UTC, dirk-thomas commented
Closing due to no further response.

2019-09-02 04:06 UTC, closed without merging